import { STATUS_BURN, STATUS_POISON, STATUS_STUN, type MoveDef } from "@pirate-battle/core";

export const MOVES: readonly MoveDef[] = [
  {
    key: "tide_surge",
    name: "Tide Surge",
    affinity: "kraken",
    basePower: 65,
    accuracy: 100,
    kind: "damage",
  },
  {
    key: "ink_cloud",
    name: "Ink Cloud",
    affinity: "kraken",
    basePower: 0,
    accuracy: 95,
    kind: "status",
    statusEffect: STATUS_POISON,
  },
  {
    key: "tentacle_lash",
    name: "Tentacle Lash",
    affinity: "kraken",
    basePower: 35,
    accuracy: 100,
    kind: "damage",
    priority: 1,
  },
  {
    key: "maelstrom",
    name: "Maelstrom",
    affinity: "kraken",
    basePower: 95,
    accuracy: 80,
    kind: "damage",
  },

  {
    key: "cannonade",
    name: "Cannonade",
    affinity: "ironclad",
    basePower: 80,
    accuracy: 90,
    kind: "damage",
  },
  {
    key: "hull_plate",
    name: "Hull Plate",
    affinity: "ironclad",
    basePower: 0,
    accuracy: 100,
    kind: "buff",
  },
  {
    key: "rivet_salvo",
    name: "Rivet Salvo",
    affinity: "ironclad",
    basePower: 50,
    accuracy: 100,
    kind: "damage",
  },
  {
    key: "iron_will",
    name: "Iron Will",
    affinity: "ironclad",
    basePower: 0,
    accuracy: 100,
    kind: "buff",
  },

  {
    key: "vanish",
    name: "Vanish",
    affinity: "phantom",
    basePower: 0,
    accuracy: 100,
    kind: "buff",
  },
  {
    key: "phantom_strike",
    name: "Phantom Strike",
    affinity: "phantom",
    basePower: 70,
    accuracy: 95,
    kind: "damage",
  },
  {
    key: "mirage",
    name: "Mirage",
    affinity: "phantom",
    basePower: 0,
    accuracy: 90,
    kind: "status",
    statusEffect: STATUS_STUN,
  },
  {
    key: "blood_fade",
    name: "Blood Fade",
    affinity: "phantom",
    basePower: 55,
    accuracy: 100,
    kind: "damage",
    priority: 1,
  },

  {
    key: "cutlass_combo",
    name: "Cutlass Combo",
    affinity: "bloodborne",
    basePower: 60,
    accuracy: 100,
    kind: "damage",
  },
  {
    key: "boarding_charge",
    name: "Boarding Charge",
    affinity: "bloodborne",
    basePower: 85,
    accuracy: 90,
    kind: "damage",
  },
  {
    key: "berserk",
    name: "Berserk",
    affinity: "bloodborne",
    basePower: 0,
    accuracy: 100,
    kind: "buff",
  },
  {
    key: "last_stand",
    name: "Last Stand",
    affinity: "bloodborne",
    basePower: 0,
    accuracy: 90,
    kind: "status",
    statusEffect: STATUS_BURN,
  },
];

export const MOVES_BY_KEY: Readonly<Record<string, MoveDef>> = Object.freeze(
  Object.fromEntries(MOVES.map((m) => [m.key, m])),
);
